Repository ucsb-cs156-m23/proj-happycows-m23-10am-4, pull requests merged in 2023-08, with the labels that each got.

#16 Buying Cows will No Longer Produce a Toast Message
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: FIXME: Needs Team Member CR

#15 docs:Links point to team instances
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: FIXME: Changes Requested

#30 FEATURE: Add incremental mutation testing for workflows 33 and 34
  .github/workflows/33-frontend-pr-mutation-testing.yml
  .github/workflows/34-frontend-main-mutation-testing.yml
Labels: Has Team Member Review, 10

#31 Degradation Rate Step is Now 0.001
  frontend/src/main/components/Commons/CommonsForm.js
Labels: 5

#34 Jobs Buttons Displays Relevant Text
  frontend/src/main/components/Jobs/InstructorReportForm.js
  frontend/src/main/components/Jobs/InstructorReportSpecificCommonsForm.js
  frontend/src/main/components/Jobs/MilkCowsJobForm.js
Labels: 5

#38 Hotfix for mutation testing with multiple changed frontend files
  .github/workflows/33-frontend-pr-mutation-testing.yml
Labels: PRIORITY, Has Team Member Review

#17 Leaderboard now shows total wealth in USD currency
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
Labels: Has Team Member Review

#32 FEATURE: Added back button to leaderboard page
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: 5, Has Team Member Review

#36 Random Greetings for Players on the Play Page
  frontend/src/assets/PlayGreetings.json
  frontend/src/main/components/Commons/CommonsPlay.js
  frontend/src/tests/components/Commons/CommonsPlay.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 5, Has Team Member Review

#55 Updated Project Name to Happy Cows
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/main/pages/LoginPage.js
  frontend/src/tests/components/Nav/Footer.test.js
  frontend/src/tests/pages/LoginPage.test.js
Labels: 5

#57 fix:Admin page story now shows the fixtures for commons
  frontend/src/stories/pages/AdminListCommonPage.stories.js
Labels: 5

#35 FEATURE: Added Capacity per User Feature
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/main/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategies.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: Has Team Member Review

#37 FEATURE: Add scheduled stat tracking for Commons
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/components/OurTable.js
  frontend/src/main/pages/AdminListCommonPage.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonStatsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/CommonStats.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/main/java/edu/ucsb/cs156/happiercows/helpers/CommonStatsCSVHelper.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/RecordCommonStatsJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/RecordCommonStatsJobFactory.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobs.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonStatsRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/services/AverageCowHealthService.java
  src/main/java/edu/ucsb/cs156/happiercows/services/CommonStatsService.java
  src/main/resources/application-development.properties
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonStatsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/RecordCommonStatsJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/RecordCommonStatsJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobsTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/AverageCowHealthServiceTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/CommonStatsServiceTests.java
Labels: 20

#63 Rename app in pom.xml
  pom.xml
Labels: Has Team Member Review

#72 Cow selling price is proportional to cow health
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 5

#66 Iain warning delete commons
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
Labels: 10

#69 Qi fix backend check
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
Labels: Has Team Member Review, requested changes done

#61 FIX: Removed 404 Error Page on Navigation and Reload
  .github/workflows/40-check-production-build.yml
  frontend/src/App.js
  frontend/src/main/pages/LoadingPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsSelect.test.js
  frontend/src/tests/components/Commons/HealthStrategiesUpdateDropdown.test.js
  frontend/src/tests/components/Jobs/InstructorReportForm.test.js
  frontend/src/tests/components/Jobs/InstructorReportSpecificCommonsForm.test.js
  frontend/src/tests/components/Jobs/SetCowHealthForm.test.js
  frontend/src/tests/components/Jobs/TestJobsForm.test.js
  frontend/src/tests/components/Jobs/UpdateCowHealthForm.test.js
  frontend/src/tests/pages/LoadingPage.test.js
Labels: Has Team Member Review, READY-for staff review, requested changes done

#67 Homepage Displays User Name
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/pages/HomePage.js
  frontend/src/stories/pages/HomePage.stories.js
  frontend/src/tests/pages/HomePage.test.js
Labels: FIXME: Needs Team Member CR, requested changes done

#91 FIX: Fixing numUsers variable issue
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/CommonsPlus.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobFactory.java
  src/main/java/edu/ucsb/cs156/happiercows/services/CommonsPlusBuilderService.java
  src/main/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategies.java
  src/main/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategy.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/CommonsPlusBuilderServiceTests.java
  src/test/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategyTests.java
Labels: Has Team Member Review, READY-for staff review

#78 BUG: Fixed PagedJobsTable Storybook
  frontend/src/main/components/Jobs/PagedJobsTable.js
  frontend/src/stories/components/Jobs/PagedJobsTable.stories.js
Labels: Has Team Member Review, READY-for staff review, requested changes done

#96 Feature: Add templates for Chat Frontend Components
  frontend/src/fixtures/chatMessageFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
  frontend/src/main/components/Chat/ChatDisplay.js
  frontend/src/main/components/Chat/ChatMessageCreate.js
  frontend/src/main/components/Chat/ChatMessageDisplay.js
  frontend/src/main/components/Chat/ChatPanel.js
  frontend/src/tests/components/Chat/ChatPanel.test.js
Labels: Has Team Member Review, READY-for staff review

#39 UI: better UI for CommonsForm
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
Labels: Has Team Member Review, READY-for staff review, requested changes done

#76 Chat Message Backend API
  src/main/java/edu/ucsb/cs156/happiercows/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ProfitsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ReportsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/SystemInfoController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserInfoController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/ChatMessage.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/ReportLine.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/User.java
  src/main/java/edu/ucsb/cs156/happiercows/helpers/ReportCSVHelper.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/SetCowHealthJobFactory.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobFactory.java
  src/main/java/edu/ucsb/cs156/happiercows/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/ChatMessageRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ReportsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/UserTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/InstructorReportJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/InstructorReportJobSingleCommonsTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/InstructorReportJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobsTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/TestJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/ReportServiceTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImplTests.java
  src/test/java/edu/ucsb/cs156/happiercows/testconfig/MockCurrentUserServiceImpl.java
Labels: Has Team Member Review, READY-for staff review, requested changes done

#98 FEATURE: ChatMessageCreate component
  frontend/src/main/components/Chat/ChatMessageCreate.js
  frontend/src/stories/components/Chat/ChatMessageCreate.stories.js
  frontend/src/tests/components/Chat/ChatMessageCreate.test.js
Labels: Has Team Member Review

#99 fix: add role check for /api/usercommons/commons/all
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: Has Team Member Review, READY-for staff review

#100 FEATURE: ChatPanel and integration into the PlayPage
  frontend/src/main/pages/PlayPage.js
  frontend/src/stories/components/Chat/ChatPanel.stories.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: Has Team Member Review, READY-for staff review
